### ISSUE TITLE
Geometry angles shall be written as optional bands

### ISSUE THREAD

**Issue by marpet** [bcdev/s3tbx-c2rcc#17]
The geometry angles shall be written as optional bands this is already possible for MODIS.
When done for other bands the naming needs to be consolidated.

**Comment by marpet** [comment]
I would suggest to use the names used in OLCI

**Comment by RolandDo** [comment]
we could do this in the C2R code, but then we must change for the other sensors also according to their naming conditions
Roland

**Comment by bcdev** [comment]
Yes. But this is not urgent.
