### ISSUE TITLE
Water leaving reflectance bands shall be consistently named rhow

### ISSUE THREAD

**Issue by marpet** [bcdev/s3tbx-c2rcc#5]
Currently the names are **_rwa_*_** or just **_reflec_*_**. These shall be named **_rhow_*_**.
The normalised ones shall be named **_rhown_*_**.
This affects also **_oos_rwa_** which will be renamed to **_oos_rhow_**

**Comment by Jackooshh** [comment]
> Currently the names are **_rwa_*_** or just **_reflec_*_**. These shall be named **_rhow_*_**. The normalised ones shall be named **_rhown_*_**. This affects also **_oos_rwa_** which will be renamed to **_oos_rhow_**

In some published papers, the band ratio such as (B4/B3) was adopted in these researches instead of chl_conc resulting from C2RCC to find the concentration of chlorophyll-a.

What is the 
In some published papers, the band ratio such as (B4/B3) was adopted in these researches instead of chl_conc resulting from C2RCC to find the concentration of chlorophyll-a.

What is the reason for that? And what is more accurate? reason for that? And what is more accurate?

**Comment by Jackooshh** [comment]
> Currently the names are **_rwa_*_** or just **_reflec_*_**. These shall be named **_rhow_*_**. The normalised ones shall be named **_rhown_*_**. This affects also **_oos_rwa_** which will be renamed to **_oos_rhow_**

In some published papers, the band ratio such as (B4/B3) was adopted in these researches instead of chl_conc resulting from C2RCC to find the concentration of chlorophyll-a.

What is the reason for that? And what is more accurate?

**Comment by marpet** [comment]
A band ratio is a simplification. IT might work in some cases and it might give you some first indication of the magnitude of the chlorophyll, but if you want to get more accurate results more complex algorithms are needed.

**Comment by Jackooshh** [comment]
Thx a lot, I understand that, but my question is it possible to adopt the chl-conc resulting from the C2RCC image procedure as a final result of chlorophyll-a concentrations to be compared with the in situ measurements in Excel?  I mean is this considered sufficient or should I use a specific band ratio?

> A band ratio is a simplification. IT might work in some cases and it might give you some first indication of the magnitude of the chlorophyll, but if you want to get more accurate results more complex algorithms are needed.

**Comment by KerstinS** [comment]
The chlorophyll concentration is derived from the absorpotion by phytoplankton. The absorption of phytoplankton is stored in the band iop_apig. The conversion follows this formular: conc_chl = iop_apig^CHL_exp * CHL_fac. You can make an comparison between the iop_apig and your in-situ data for chlorophyll. if you find another relationship than the one c2rcc provides, you can change the parameters for CHL_exp and CHL_fac in the processor.

**Comment by marpet** [comment]
@Jackooshh Thanks for your interest in C2RCC. But it would be best if you put your questions into the SNAP Forum.
https://forum.step.esa.int/c/s3tbx/7

This is the repository of an old abandoned c2rcc.
The most recent source code can be found here: https://github.com/senbox-org/s3tbx/tree/master/s3tbx-c2rcc
